nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
        - "443:443"
node1:
    build: ./node
    links:
        - mongo
    ports:
        - "4000"
node2:
    build: ./node
    links:
        - mongo
    ports:
        - "4000"
node3:
    build: ./node
    links:
        - mongo
    ports:
        - "4000"
mongo:
    image: mongo
    ports:
        - "27017"
