nginx:
    build: ./nginx
    links:
        - node1:node1
    ports:
        - "80:80"
        - "443:443"
node1:
    build: ./node
    links:
        - mongo
    ports:
        - "4000"
mongo:
    image: mongo
    ports:
        - "27017"
